const controlLabel = {
  estateNum: '房产证号',
  addressCode: '房产证地址',
  addressDesc: '详细地址',
  estateTypeCode: '房屋性质',
  rentConditionCode: '房屋居住情况',
  obtainDate: '持有房产时间',
  completedDt: '建成年代',
  floor: '所在楼层（层）',
  totalFloor: '总楼层数（层）',
  coownersCnt: '共有产权人数',
  propertySharePercent: '借款人产权份额（%）',
  houseSizeMeas: '面积（平方米）',
  communityName: '小区名称',
  inputAverageAmt: '人工录入均价',
  slAverageAmt: '世联均价',
  estateSourceCode: '房产来源',
  bankEvaluationAmt: '银行评估价',
  incomeBase: '房产认定价值',
  totalPriceAmt: '房产总价',
  mortgageInd: '是否在押',
  mortgageTypeCd: '一押类型',
  pledgeTypeCd: '一押抵押方式',
  orgCode: '一押抵押机构名称',
  orgType: '一押机构类型',
  creditAmt: '一押授信金额',
  loanBalanceAmt: '一押贷款余额',
  loanUtilizeTypeCd: '贷款发放方式',
  maxAmtMortgageInd: '是否最高额抵押',
  pledgeAmt: '一押抵押金额',
  preStartedDt: '一押放款日期',
  preEndDt: '一押贷款到期日期',
  repaymentCd: '一押还款方式',
  mortgageBorrowerCd: '一押贷款借款人',
  houseEvaluationAmt: '一押房产评估值',
  secondMortgageInd: '当前是否有二押',
  secondMortgageTypeCd: '二押类型',
  secondPledgeTypeCd: '二押抵押方式',
  secondOrgName: '二押机构名称',
  secondOrgType: '二押机构类型',
  secondRepaymentCd: '二押还款方式',
  secondMortgageBorrowerCd: '二押贷款借款人',
  secondCreditAmt: '二押授信金额',
  secondLoanBalanceAmt: '二押贷款余额'
};

const PlusLoanLabelList = [
  "mortgageTypeCd",
  "pledgeTypeCd",
  "orgType",
  "repaymentCd",
  "mortgageBorrowerCd",
  "preStartedDt",
  "preEndDt",
  "loanBalanceAmt",
  "creditAmt",
  "secondMortgageTypeCd",
  "secondPledgeTypeCd",
  "secondOrgType",
  "secondRepaymentCd",
  "secondMortgageBorrowerCd"
];
const MulLibDefault = [
  'pledge_type_cd',
  'jgcode_mortgage',
  'rent_condition_code',
  'repayment_cd',
  'estate_type_code',
  'certificate_type_code',
  'mortgage_type_cd',
  'org_type',
  'second_org_type',
  'mortgage_borrower_cd',
  'loan_utilize_type_cd'
];
const MulLibPlusLoan = [
  'second_mortgage_type_cd',
  'second_repayment_cd',
  'estate_source_code',
  'borrower_relationship_code'
];
export {
  controlLabel,
  PlusLoanLabelList,
  MulLibDefault,
  MulLibPlusLoan
};
